import AddStudent from "../components/AddStudent";

export default GlobalStrings = {
    welcomeSchool: "Welcome to My School",
    enerStudentName: "Enter Student Name",
    enerStudentId: "Enter Student Id",
    enerStudentBranch: "Enter Student Class",
    enerStudentPhone: "Enter Student Phone Number",
    add: "Add",
    addStudent: "Add Student",
    students: "Students",
    sectionStudents: "Class Wise Students",
    selectGender: "Select Gender",
    enterEmail: "Enter email",
    selectDate: "Select Date",
    login: "Login",
    enterUserName: "Enter Username",
    enterName: "Enter Name",
    enterPassword: "Enter Password",
    enterConfPassword: "Enter ConfirmPassword",
    passwordNotMatching: "Passwords Not matching",
    invalidcredi: "Please enter valid credintials",
    deleteStudent: "Delete Student",
    deleteStudentConf: "Do you want to delete",
    studentDeleteSuccess: "Student Deleted Successfully",
    studentUpdatesuccess: "Student Updated Successfully",
    studentAddedsuccess: "Student Added Successfully",
    adminAddedsuccess: "Admin Added Successfully",
    selectClass: "Select Class",
    doYouwanntToLogout: "Do You want to logout ?",
    adminRegister: "Admin Registration",
    registerAdmin:'Register Admin',

    //placeHolders
    email: "Email",
    studentId: "Student Id",
    dob: "Date Of Birth",
    gender: "Gender",
    class: "Class",
    phoneNo: "Phone Number",
    name: "Name",
    address: "Address",
    cpwd: "Confirm Password",
    pwd: "Password",
    uname: "Username"
}